<?php

$accepted_currencies = array(
        'USD' => 'USD',
        'GBP' => 'GBP',
        'EUR' => 'EUR',
        'AUD' => 'AUD',
        'CAD' => 'CAD',
        'NZD' => 'NZD',
        'MULTI' => 'MULTI',
);

$currency_processor = array(
        'USD' => '1',
        'GBP' => '1',
        'EUR' => '1',
        'AUD' => '1',
        'CAD' => '3',
        'NZD' => '1',
        'MULTI' => NULL,
);
