<?php

/** 
* All code is Copyright 2011 by the original authors.
* 
*  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*/

$accepted_currencies = array(
        'USD' => 'USD',
        'GBP' => 'GBP',
        'EUR' => 'EUR',
        'AUD' => 'AUD',
        'CAD' => 'CAD',
        'NZD' => 'NZD',
        'MULTI' => 'MULTI',
);

$currency_processor = array(
        'USD' => '1',
        'GBP' => '1',
        'EUR' => '1',
        'AUD' => '1',
        'CAD' => '3',
        'NZD' => '1',
        'MULTI' => NULL,
);
